services:
  db_prod:
    image: alpine
    command: sleep infinity
    labels:
      - prometheus.job=db
      - prometheus.labels.env=production

  db_dev:
    image: alpine
    command: sleep infinity
    labels:
      - prometheus.job=db
      - prometheus.labels.env=dev

  prometheus_docker_discovery:
    image: iterait/prometheus-docker-discovery:master
    ports:
      - 8000:8000
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
